### PR TITLE
Add shortcuts

### PR DESCRIPTION
**Pull request by mleo2003**
Add shortcuts for copying note title from list, erase a word with standard shortcut.

### CODE REVIEW

**Comment by mleo2003** [comment]
Added the Control-Delete shortcut as well as Control-Backspace.

This should satisfy #165

**Comment by yuuki0xff** [comment]
Thank you for your contribution.
I found a bug in `cmd_text_copy()`.  In the Linux environment, it always copies the note title on the top of list. The intention is to copy the title of selected note, right?

**Comment by mleo2003** [comment]
Ah, yes. That is the intention. I'm not sure why the Linux version is different than the Windows version in this regard. I'll see if I can setup something to test it with.

**Comment by mleo2003** [comment]
After a quick check in Windows, I can confirm this is a bug for multiple platforms, and I know why: I'm getting the event data for a click/mouse event, and then applying it to a keyboard shortcut. My original testing was a click, then a Control+C on the item, which works. As it is now, it just copies whichever note title your mouse hovers over, even if not selected...

I'll try to fix, or I can just remove from this PR and add it back later once I actually implement it correctly, instead of copying the click event code right above it...

**Comment by mleo2003** [comment]
It helps to just use the built-in idx that is recorded on every note change from that menu, instead of blindly copy/pasting code from other functions...

Should be ready to go @yuuki0xff

**Pull request merged**
