### PR TITLE
Added the option to specify a different config file via a cmd line switch

### PR DESCRIPTION
**Pull request by LeHack**
One may want to keep a couple of sets of notes, this makes it possible by writing a set of config files, one for each set of notes and then running nvpy with the appropriate config file via the --cfg switch (also added very basic --help).

### CODE REVIEW

**Comment by cpbotha** [comment]
If you would be willing to use `argparse` instead of `getopt`, and use underscore naming for the argument parsing method (see PEP8), I would like to merge this.

**Comment by LeHack** [comment]
Sure, I'll fix it later today and merge in the current master since I see it got out-of-sync.

**Comment by cpbotha** [comment]
Much appreciated! (this is the first time in ages I've been able to work on nvpy maintenance)

**Comment by LeHack** [comment]
Done. Indeed this was a much better choice. I'm still learning my ways around, so thanks for the help.

**Comment by cpbotha** [comment]
Thanks for your PR. Please study the changes I made on top of your work for future reference: https://github.com/cpbotha/nvpy/commit/eb53979e518f49f782248fc9b275fe094110e546

**Pull request merged**
